### ISSUE TITLE
Problem with 2.0.0-34 firmware version 

### ISSUE THREAD

**Issue by koldavideo** [koalazak/dorita980#14]
Hello,
Thank you for a great software for ROOMBA 980. Unfortunately, I have a Roomba sw ver. 2.0.0-34.
Script getpassword don´t work. Can You help me?
Thank You.
Peter
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'getpassword',
1 verbose cli   '10.0.1.55' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'pregetpassword', 'getpassword', 'postgetpassword' ]
5 info lifecycle dorita980@2.5.1~pregetpassword: dorita980@2.5.1
6 silly lifecycle dorita980@2.5.1~pregetpassword: no script for pregetpassword, continuing
7 info lifecycle dorita980@2.5.1~getpassword: dorita980@2.5.1
8 verbose lifecycle dorita980@2.5.1~getpassword: unsafe-perm in lifecycle true
9 verbose lifecycle dorita980@2.5.1~getpassword: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\kolarikp\Dokumenty\dorita980-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\ProgramData\Lenovo\ReadyApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\CA\SC\Csam\SockAdapter\bin;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\kolarikp\AppData\Roaming\npm
10 verbose lifecycle dorita980@2.5.1~getpassword: CWD: C:\Users\kolarikp\Dokumenty\dorita980-master
11 silly lifecycle dorita980@2.5.1~getpassword: Args: [ '/d /s /c', 'node ./bin/getpassword.js "10.0.1.55"' ]
12 silly lifecycle dorita980@2.5.1~getpassword: Returned: code: 1  signal: null
13 info lifecycle dorita980@2.5.1~getpassword: Failed to exec getpassword script
14 verbose stack Error: dorita980@2.5.1 getpassword: `node ./bin/getpassword.js "10.0.1.55"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid dorita980@2.5.1
16 verbose cwd C:\Users\kolarikp\Dokumenty\dorita980-master
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "getpassword" "10.0.1.55"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error dorita980@2.5.1 getpassword: `node ./bin/getpassword.js "10.0.1.55"`
22 error Exit status 1
23 error Failed at the dorita980@2.5.1 getpassword script 'node ./bin/getpassword.js "10.0.1.55"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dorita980 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/getpassword.js "10.0.1.55"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dorita980
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dorita980
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by koldavideo** [comment]
I'm sorry, I missed thread : roomba 980 firmware 2.0.0-34 ready?
