### ISSUE TITLE
Issue retrieving password Cloud or local method

### ISSUE THREAD

**Issue by Bastien42** [koalazak/dorita980#178]
i can't seem to retrieve the password of my roomba that wasn't the case somtime ago here is a log of the command run 

![Screenshot 2023-07-13 164025](https://github.com/koalazak/dorita980/assets/37946663/a8975af0-b74e-43f2-9169-495bff75edd4)

**Comment by aelharda** [comment]
same error as the above

**Comment by FidgetyRat** [comment]
Same

**Comment by munkien** [comment]
Here too :(
iRobot I7 + clean base

![image](https://github.com/koalazak/dorita980/assets/55032909/fa32a343-2d63-4aa9-a0ca-b19d6bfd806a)

**Comment by bredowmax** [comment]
Same error message as @munkien reported

`Fatal error login into iRobot account. Please check your credentials or API Key.
An error occurred (AccessDeniedException) when calling the GetSecretValue operation: Access to KMS is not allowed`

**Comment by jayvarner** [comment]
I also get the error described here. I was able to use this [Python Lib](https://github.com/NickWaterton/Roomba980-Python). There are instructions for [getting credentials from the cloud](https://github.com/NickWaterton/Roomba980-Python#getting-your-usernameblid-and-password-from-the-irobot-cloud). Apologies for suggesting a another project and not adding anything helpful to the issue here.

**Comment by Bastien42** [comment]
> I also get the error described here. I was able to use this [Python Lib](https://github.com/NickWaterton/Roomba980-Python). There are instructions for [getting credentials from the cloud](https://github.com/NickWaterton/Roomba980-Python#getting-your-usernameblid-and-password-from-the-irobot-cloud). Apologies for suggesting a another project and not adding anything helpful to the issue here.


yeah i tried this method too and this returns an error too

```
2023-07-17 17:09:42 INFO [Roomba.Password] Getting Roomba information from iRobot aws cloud...
Traceback (most recent call last):
  File "C:\Users\Bastien\Desktop\Roomba980-Python-master (1)\Roomba980-Python-master\roomba\password.py", line 294, in <module>
    main()
  File "C:\Users\Bastien\Desktop\Roomba980-Python-master (1)\Roomba980-Python-master\roomba\password.py", line 291, in main
    get_passwd.get_password()
  File "C:\Users\Bastien\Desktop\Roomba980-Python-master (1)\Roomba980-Python-master\roomba\password.py", line 117, in get_password
    from getcloudpassword import irobotAuth
  File "C:\Users\Bastien\Desktop\Roomba980-Python-master (1)\Roomba980-Python-master\roomba\getcloudpassword.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by FidgetyRat** [comment]
> I also get the error described here. I was able to use this [Python Lib](https://github.com/NickWaterton/Roomba980-Python). There are instructions for [getting credentials from the cloud](https://github.com/NickWaterton/Roomba980-Python#getting-your-usernameblid-and-password-from-the-irobot-cloud). Apologies for suggesting a another project and not adding anything helpful to the issue here.

Don't apologize. Im sure most people here just want a solution and the python lib was that.

**Comment by RJiraya** [comment]
Hello !

Did you retry today ? The problems seems to be fixed by iRobot team !

It's working on my side.

**Comment by Bastien42** [comment]
well yes you're right whatever was the issue now it works with doitu980 too
