### ISSUE TITLE
Times out

### ISSUE THREAD

**Issue by nelsonblaha** [koalazak/dorita980#73]
I get a little bit of info out of my 980 with firmware 2.4.6-3, but no password:

```
Robot Data:
{ ver: '3',
  hostname: 'Roomba-30F5C32071508660',
  robotname: 'Roomba',
  ip: '192.168.86.92',
  mac: '28:C2:DD:EA:D2:12',
  sw: 'v2.4.6-3',
  sku: 'R98----',
  nc: 0,
  proto: 'mqtt',
  cap: 
   { pose: 1,
     ota: 2,
     multiPass: 2,
     carpetBoost: 1,
     pp: 1,
     binFullDetect: 1,
     langOta: 1,
     maps: 1,
     edge: 1,
     eco: 1,
     svcConf: 1 },
  blid: 'blahblahblah' }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.86.92:8883
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

npm ERR! Linux 4.15.0-38-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "getpassword" "192.168.86.92"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! dorita980@3.0.12 getpassword: `node ./bin/getpassword.js "192.168.86.92"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dorita980@3.0.12 getpassword script 'node ./bin/getpassword.js "192.168.86.92"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dorita980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/getpassword.js "192.168.86.92"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dorita980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dorita980
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ben/dorita980/npm-debug.log
```

**Comment by nelsonblaha** [comment]
npm-debug.log: 

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'getpassword',
1 verbose cli   '192.168.86.92' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'pregetpassword', 'getpassword', 'postgetpassword' ]
5 info lifecycle dorita980@3.0.12~pregetpassword: dorita980@3.0.12
6 silly lifecycle dorita980@3.0.12~pregetpassword: no script for pregetpassword, continuing
7 info lifecycle dorita980@3.0.12~getpassword: dorita980@3.0.12
8 verbose lifecycle dorita980@3.0.12~getpassword: unsafe-perm in lifecycle true
9 verbose lifecycle dorita980@3.0.12~getpassword: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ben/src/dorita980/node_modules/.bin:/home/ben/src/couchdb-utils/bin:/home/ben/src/dev-tools$
10 verbose lifecycle dorita980@3.0.12~getpassword: CWD: /home/ben/src/dorita980
11 silly lifecycle dorita980@3.0.12~getpassword: Args: [ '-c', 'node ./bin/getpassword.js "192.168.86.92"' ]
12 silly lifecycle dorita980@3.0.12~getpassword: Returned: code: 1  signal: null
13 info lifecycle dorita980@3.0.12~getpassword: Failed to exec getpassword script
14 verbose stack Error: dorita980@3.0.12 getpassword: `node ./bin/getpassword.js "192.168.86.92"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid dorita980@3.0.12
16 verbose cwd /home/ben/src/dorita980
17 error Linux 4.15.0-38-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "getpassword" "192.168.86.92"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error dorita980@3.0.12 getpassword: `node ./bin/getpassword.js "192.168.86.92"`
22 error Exit status 1
23 error Failed at the dorita980@3.0.12 getpassword script 'node ./bin/getpassword.js "192.168.86.92"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dorita980 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/getpassword.js "192.168.86.92"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dorita980
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dorita980
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by nelsonblaha** [comment]
Fixed by soft-resetting Roomba (holding down clean button for 10 seconds)
