### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by JohnnySlagle** [koalazak/dorita980#79]
I'm having issues connecting to the robot: I cannot getpassword or use local password discovery. 

For the former, I get the error: "Error getting password. Follow the instructions and try again." And the latter:

`Looking for robots...
Robot found! with blid/username: 3166480C80127680
{ ver: '3',
  hostname: 'Roomba-3166480C80127680',
  robotname: 'Lupe',
  ip: '192.168.1.2',
  mac: 'D0:C5:D3:3A:9F:D9',
  sw: 'v2.4.6-3',
  sku: 'R960020',
  nc: 0,
  proto: 'mqtt',
  cap: 
   { pose: 1,
     ota: 2,
     multiPass: 2,
     pp: 1,
     binFullDetect: 1,
     langOta: 1,
     maps: 1,
     edge: 1,
     eco: 1,
     svcConf: 1 } }
/Users/slagle/node_modules/dorita980/lib/v2/local.js:30
    throw e;
    ^

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/Users/slagle/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/Users/slagle/node_modules/mqtt/lib/client.js:350:12)
    at work (/Users/slagle/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/Users/slagle/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/Users/slagle/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/slagle/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/Users/slagle/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)
`

I'm wondering if there is something happening with my router which is preventing the connection? I have a Netgear Orbi and have had issues with it in the past blocking connections (but being a network n00b didn't solve them). Any ideas/help? Thanks! :)

**Comment by koalazak** [comment]
Hi, what version of node and npm do you have?

first you need to [obtain your password](https://github.com/koalazak/dorita980#how-to-get-your-usernameblid-and-password) running this commands:
```
$ git clone https://github.com/koalazak/dorita980.git
$ cd dorita980
$ npm install
$ npm run getpassword 192.168.1.2
```
and follow the onscreen instructions to complete the process and get your password.
Once you get the password, you can use it in dorita980 examples: https://github.com/koalazak/dorita980#quick-start-via-local-request-on-your-lan
