### ISSUE TITLE
Problems with i7+

### ISSUE THREAD

**Issue by thorazine-12** [koalazak/dorita980#81]
Hello,

I have i7+ with 1.6.6 firmware (EMEA). I'm able to do basic actions using Local API (start, pause, stop, dock); the only method that works is getWirelessStatus.
All others (getSys, getWeek, getPreferences etc.) return nothing.

Also Cloud access doesn't work - problem with resolving irobot.axeda.com :/
Result of myRobotViaCloud.getStatus():

```
pi@raspberrypi:~/Downloads/dorita980 $ node myapp.js
{ RequestError: Error: getaddrinfo ENOTFOUND irobot.axeda.com irobot.axeda.com:443
    at new RequestError (/home/pi/Downloads/dorita980/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/pi/Downloads/dorita980/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/pi/Downloads/dorita980/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/pi/Downloads/dorita980/node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.onRequestError (/home/pi/Downloads/dorita980/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  name: 'RequestError',
  message:
   'Error: getaddrinfo ENOTFOUND irobot.axeda.com irobot.axeda.com:443',
  cause:
   { Error: getaddrinfo ENOTFOUND irobot.axeda.com irobot.axeda.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'irobot.axeda.com',
     host: 'irobot.axeda.com',
     port: 443 },
  error:
   { Error: getaddrinfo ENOTFOUND irobot.axeda.com irobot.axeda.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'irobot.axeda.com',
     host: 'irobot.axeda.com',
     port: 443 },
  options:
   { method: 'GET',
     headers:
      { 'User-Agent': 'aspen%20production/2618 CFNetwork/758.3.15 Darwin/15.4.0',
        Accept: '*/*',
        'Accept-Language': 'en-us',
        'ASSET-ID': 'ElPaso@irobot!F1FFBE8B5FCE439CA080273553DFC57A' },
     uri:
      'https://irobot.axeda.com/services/v1/rest/Scripto/execute/AspenApiRequest?blid=F1FFBE8B5FCE439CA080273553DFC57A&robotpwd=:1:1552928199:fCYdULh6r9Zs14ES&method=getStatus',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
```

So what am I doing wrong?

**Comment by koalazak** [comment]
seems liek the host irobot.axeda.com is down

**Comment by thorazine-12** [comment]
but how can I resolve problem with getSys, getWeek etc. not working using local API?

**Comment by koalazak** [comment]
Hi @thorazine-12 , can you run this code and share the output please?

```javascript
const dorita980 = require('dorita980');
  const myLocalRobot = new dorita980.Local('blid_here', 'password_here', 'ip_here');

  myLocalRobot.on('connect', () => { 
    console.log('connected'); 
    myLocalRobot.on('packetreceive', packet =>  {
      packet.payload = JSON.parse(packet.payload);
      console.log(JSON.stringify(packet, null, 2));
    });
  });
```

thanks

**Comment by thorazine-12** [comment]
Sure I can, here is my config and results of script:

```
Robot Data:
{ ver: '3',
  hostname: 'iRobot-F1FFBE8B5FCE439CA080273553DFC57A',
  robotname: 'Roomba',
  robotid: 'F1FFBE8B5FCE439CA080273553DFC57A',
  ip: '192.168.1.12',
  mac: '50:14:79:01:5B:AA',
  sw: 'lewis+1.6.6+lewis-day-0-ota+29',
  sku: 'i755040',
  nc: 0,
  proto: 'mqtt',
  cap:
   { binFullDetect: 1,
     dockComm: 1,
     maps: 3,
     edge: 0,
     area: 1,
     eco: 1,
     multiPass: 2,
     pose: 1,
     team: 1,
     pp: 0,
     '5ghz': 1,
     prov: 3,
     sched: 1,
     svcConf: 1,
     ota: 2,
     log: 2 },
  blid: '.........................' }
Password=> .......................... <= Yes, all this string.
Use this credentials in dorita980 lib :)
```

```
pi@raspberrypi:~/Downloads/dorita980 $ node dorita-test.js
connected
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 3172,
  "topic": "$aws/things/F1FFBE8B5FCE439CA080273553DFC57A/shadow/update",
  "payload": {
    "state": {
      "reported": {
        "batPct": 100,
        "batteryType": "F12432832R",
        "bbchg": {
          "nLithF": 0,
          "nChgOk": 21,
          "aborts": [
            0,
            0,
            0
          ],
          "smberr": 0
        },
        "bbchg3": {
          "estCap": 1826,
          "nAvail": 37,
          "hOnDock": 619,
          "avgMin": 71
        },
        "bbmssn": {
          "aCycleM": 48,
          "nMssnF": 1,
          "nMssnC": 11,
          "nMssnOk": 19,
          "aMssnM": 90,
          "nMssn": 31
        },
        "bbnav": {
          "aMtrack": 0,
          "nGoodLmrks": 0,
          "aGain": 0,
          "aExpo": 0
        },
        "bbpause": {
          "pauses": [
            41,
            34,
            25,
            1,
            5,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "bbrun": {
          "nEvacs": 24,
          "min": 6,
          "sqft": 154,
          "nPanics": 38,
          "hr": 31,
          "nScrubs": 0,
          "nStuck": 5,
          "nPicks": 5,
          "nMBStll": 0,
          "nWStll": 1,
          "nCBump": 0,
          "nCliffsF": 179,
          "nCliffsR": 0
        },
        "bbswitch": {
          "nBumper": 31349,
          "nDrops": 305,
          "nDock": 15,
          "nSpot": 4,
          "nClean": 11
        },
        "bbsys": {
          "min": 38,
          "hr": 33
        },
        "bin": {
          "present": true,
          "full": false
        },
        "binPause": true,
        "cap": {
          "binFullDetect": 1,
          "dockComm": 1,
          "maps": 3,
          "edge": 0,
          "area": 1,
          "eco": 1,
          "multiPass": 2,
          "pose": 1,
          "team": 1,
          "pp": 0,
          "5ghz": 1,
          "prov": 3,
          "sched": 1,
          "svcConf": 1,
          "ota": 2,
          "log": 2
        },
        "carpetBoost": false,
        "cleanMissionStatus": {
          "cycle": "none",
          "phase": "charge",
          "expireM": 90,
          "rechrgM": 0,
          "error": 0,
          "notReady": 0,
          "mssnM": 0,
          "sqft": 0,
          "initiator": "localApp",
          "nMssn": 31
        },
        "cleanSchedule2": [],
        "cloudEnv": "prod",
        "connected": true,
        "country": "PL",
        "deploymentState": 0,
        "dock": {
          "known": true,
          "pn": "unknown",
          "state": 301,
          "id": "45229698311701166376610816949787168",
          "fwVer": "0.10.20"
        },
        "ecoCharge": false,
        "hwPartsRev": {
          "csscID": 0,
          "mobBrd": 7,
          "navSerialNo": "CF08C03BS",
          "wlan0HwAddr": "50:14:79:01:5b:aa"
        },
        "langs": [
          {
            "cs-CZ": 0
          },
          {
            "da-DK": 1
          },
          {
            "de-DE": 2
          },
          {
            "en-GB": 3
          },
          {
            "en-US": 4
          },
          {
            "es-ES": 5
          },
          {
            "es-XL": 6
          },
          {
            "fi-FI": 7
          },
          {
            "fr-CA": 8
          },
          {
            "fr-FR": 9
          },
          {
            "he-IL": 10
          },
          {
            "it-IT": 11
          },
          {
            "ja-JP": 12
          },
          {
            "nb-NO": 13
          },
          {
            "nl-NL": 14
          },
          {
            "pl-PL": 15
          },
          {
            "pt-BR": 16
          },
          {
            "pt-PT": 17
          },
          {
            "ru-RU": 18
          },
          {
            "sv-SE": 19
          },
          {
            "zh-CN": 20
          },
          {
            "zh-HK": 21
          },
          {
            "zh-TW": 22
          }
        ],
        "language": 15,
        "lastCommand": {
          "command": "addrobotdone"
        },
        "mapUploadAllowed": true,
        "name": "Roomba",
        "noAutoPasses": false,
        "noPP": false,
        "openOnly": false,
        "pmapLearningAllowed": true,
        "pmaps": [
          {
            "cf7X1msZQwC5t06VY_g_LA": "190415T173302"
          }
        ],
        "rankOverlap": 15,
        "schedHold": false,
        "secureBoot": {
          "log": 2,
          "flip": 0,
          "sbl1Ver": "B3.2.0_PPUB",
          "stublVer": "B3.2.0_PPUB",
          "efuse": 1,
          "blType": 1,
          "enforce": 2,
          "lastRst": "8000000080",
          "recov": "linux+1.1.7+lewis-day-0-ota+18",
          "idSwitch": 0
        },
        "sku": "i755040",
        "softwareVer": "lewis+1.6.6+lewis-day-0-ota+29",
        "subModSwVer": {
          "nav": "lewis-nav+1.6.6-EPMF+build-HEAD-c0844843f3c+29",
          "mob": "1.6.6-XX+build-HEAD-c0844843f3c+29",
          "pwr": "0.4.4+build-HEAD-c0844843f3c+29",
          "sft": "1.0.0+Lewis-Builds/Lewis-Certified-Safety/lewis-safety-dd0a1e9a2e8+13",
          "linux": "linux+1.1.12+lewis-day-0-ota+29",
          "con": "1.1.18-tags/release-1.1.18@7ceb381/build"
        },
        "svcEndpoints": {
          "svcDeplId": "v011"
        },
        "timezone": "Europe/Warsaw",
        "tls": {
          "tzbChk": 1,
          "privKType": 1,
          "lcCiphers": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            50380848,
            50380847
          ]
        },
        "twoPass": false,
        "tz": {
          "ver": 6,
          "events": [
            {
              "dt": 1541073600,
              "off": 60
            },
            {
              "dt": 1553994001,
              "off": 120
            },
            {
              "dt": 1572138001,
              "off": 60
            }
          ]
        },
        "vacHigh": false
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 603,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "netinfo": {
          "dhcp": true,
          "addr": "192.168.1.12",
          "mask": "255.255.255.0",
          "gw": "192.168.1.1",
          "dns1": "192.168.1.1",
          "dns2": "0.0.0.0",
          "bssid": "4c:ed:fb:5a:77:68",
          "sec": 4
        },
        "ntphosts": "0.irobot.pool.ntp.org 1.irobot.pool.ntp.org 2.irobot.pool.ntp.org 3.irobot.pool.ntp.org",
        "sdiscUrl": "https://disc-prod.iot.irobotapi.com/v1/robot/discover?robot_id=F1FFBE8B5FCE439CA080273553DFC57A&country_code=PL&sku=i755040",
        "signal": {
          "rssi": -53,
          "snr": 37,
          "noise": -90
        },
        "wifistat": {
          "cloud": 14,
          "wifi": 1,
          "uap": false
        },
        "wlcfg": {
          "sec": 4,
          "ssid": "736F6D656E6574"
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -52,
          "snr": 38,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -53,
          "snr": 37,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -52,
          "snr": 38,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -53,
          "snr": 37,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -52,
          "snr": 38,
          "noise": -90
        }
      }
    }
  }
}

{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -53,
          "snr": 37,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -52,
          "snr": 38,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -53,
          "snr": 37,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -52,
          "snr": 38,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -53,
          "snr": 37,
          "noise": -90
        }
      }
    }
  }
}

{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -52,
          "snr": 38,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -53,
          "snr": 37,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -52,
          "snr": 38,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -53,
          "snr": 37,
          "noise": -90
        }
      }
    }
  }
}
{
  "cmd": "publish",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 83,
  "topic": "wifistat",
  "payload": {
    "state": {
      "reported": {
        "signal": {
          "rssi": -52,
          "snr": 38,
          "noise": -90
        }
      }
    }
  }
}
```

**Comment by koalazak** [comment]
ok the problem is those methods are waiting for properties in the state that are not there in i7+ robots (like `uiSwVer` and others). So never return the state. (they are present in 980 robots)
So, I recomend to you just use the `getRobotState(['fieldYouWant')` method to get the system properties you are looking for.
To be clear, those methods (getSys, getWeek, getPreferences) just wait for some properties in the state and then return that fields. For example `getWeek()` is waiting for `cleanSchedule` in the state and i7 robots has `cleanSchedule2` propertie but not `cleanSchedule`. To emulate getWeek() in i7 robots use `getRobotState(['cleanSchedule2')`.

I will try to fix this in next version.

thank you
